version: 2

before:
  hooks:
    - go generate ./...

builds:
  - id: kavun
    binary: kavun
    dir: ./cmd/kavun
    ldflags:
      - -s -w -X cmd/kavun.version={{.Version}} -X cmd/kavun.commit={{.Commit}} -X cmd/kavun.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
