words = [
    "alc",
    "brack",
    "cfn",
    "cln",
    "cta",
    "defl",
    "dsts",
    "fprint",
    "funcs",
    "getl",
    "insts",
    "loope",
    "loopl",
    "mul",
    "replc",
    "rta",
    "scopl",
    "setl",
    "shl",
    "stmts",
    "tracec",
    "untracec",
]
