package core

import (
	"encoding/binary"
	"fmt"

	"github.com/jokruger/kavun/core/value"
	"github.com/jokruger/kavun/errs"
)

// NOTE: builtin functions are addressed by the index stored in Value.Data, not by Value.Ptr!

type BuiltinFunction struct {
	Func     NativeFunc
	Module   string
	Name     string
	Arity    int
	Variadic bool
	Pure     bool
}

// NewBuiltinFunction creates a new builtin function object.
// name is the name of the function.
// fn is the native function to be called.
// arity is the number of arguments the function takes.
// variadic is true if the function takes a variable number of arguments, in which case arity is the minimum number of arguments required.
// pure is true if the function does not have side effects, does not rely on external state, and always returns the same output for the same input.
func NewBuiltinFunction(name string, fn NativeFunc, arity int, variadic bool, pure bool) *BuiltinFunction {
	return &BuiltinFunction{
		Func:     fn,
		Name:     name,
		Arity:    arity,
		Variadic: variadic,
		Pure:     pure,
	}
}

// BuiltinFunctionValue creates new boxed builtin function value.
func BuiltinFunctionValue(id uint64) Value {
	return Value{
		Type:      value.BuiltinFunction,
		Immutable: true,
		Data:      id,
	}
}

var TypeBuiltinFunction = ValueTypeDescr{
	Name:         builtinFunctionTypeName,                                    // PURE by contract
	String:       func(v Value) string { return builtinFunctionTypeName(v) }, // PURE by contract
	EncodeBinary: builtinFunctionTypeEncodeBinary,                            // PURE by contract
	DecodeBinary: builtinFunctionTypeDecodeBinary,                            // IMPURE by contract (mutates target)
	IsTrue:       ConstHook(true),                                            // PURE by contract
	IsCallable:   ConstHook(true),                                            // PURE by contract
	IsVariadic:   builtinFunctionTypeIsVariadic,                              // PURE by contract
	Arity:        builtinFunctionTypeArity,                                   // PURE by contract
	Call:         builtinFunctionTypeCall,                                    // CALLABLE-DEPENDENT by contract
	MethodCall:   builtinFunctionTypeMethodCall,                              // PURE by contract with higher-order rule caveat (see docs/purity.md)
}

func builtinFunctionTypeName(v Value) string {
	o := BuiltinFunctions[v.Data]
	if o.Variadic {
		if o.Module != "" {
			return fmt.Sprintf("<builtin-function:%s.%s/%d+>", o.Module, o.Name, o.Arity)
		}
		return fmt.Sprintf("<builtin-function:%s/%d+>", o.Name, o.Arity)
	}
	if o.Module != "" {
		return fmt.Sprintf("<builtin-function:%s.%s/%d>", o.Module, o.Name, o.Arity)
	}
	return fmt.Sprintf("<builtin-function:%s/%d>", o.Name, o.Arity)
}

func builtinFunctionTypeEncodeBinary(v Value) ([]byte, error) {
	out := make([]byte, 8)
	binary.LittleEndian.PutUint64(out, v.Data)
	return out, nil
}

func builtinFunctionTypeDecodeBinary(v *Value, data []byte) error {
	if len(data) != 8 {
		return fmt.Errorf("builtin function: expected 8 bytes, got %d", len(data))
	}
	v.Data = binary.LittleEndian.Uint64(data)
	return nil
}

func builtinFunctionTypeIsVariadic(v Value) bool {
	// no need to check if the index is valid, since it was generated by system
	return BuiltinFunctions[v.Data].Variadic
}

func builtinFunctionTypeArity(v Value) int {
	// no need to check if the index is valid, since it was generated by system
	return BuiltinFunctions[v.Data].Arity
}

// CALLABLE-DEPENDENT: purity is a property of the specific BuiltinFunction being called (see the Pure field). The
// optimizer folds Call only when the callable is a BuiltinFunction with Pure=true. See docs/purity.md.
func builtinFunctionTypeCall(vm VM, v Value, args []Value) (Value, error) {
	// no need to check if the index is valid or .Func is not nil, since it was generated by system
	return BuiltinFunctions[v.Data].Func(vm, args)
}

// PURE by contract with higher-order rule caveat (see docs/purity.md)
func builtinFunctionTypeMethodCall(vm VM, v Value, name string, args []Value) (Value, error) {
	switch name {
	case "copy":
		if len(args) != 0 {
			return Undefined, errs.NewWrongNumArgumentsError(name, "0", len(args))
		}
		// it is always immutable, so we can return the same value
		return v, nil

	default:
		return Undefined, errs.NewInvalidMethodError(name, v.TypeName())
	}
}
