package core

import (
	"encoding/binary"
	"fmt"
	"unsafe"

	"github.com/jokruger/kavun/core/value"
	"github.com/jokruger/kavun/errs"
)

type BuiltinFunction struct {
	Func     NativeFunc
	Module   string
	Name     string
	Arity    int8
	Variadic bool
}

func NewBuiltinFunctionValue(name string, fn NativeFunc, arity int8, variadic bool) Value {
	o := &BuiltinFunction{Func: fn, Name: name, Arity: arity, Variadic: variadic}
	return Value{Type: value.BuiltinFunction, Immutable: true, Ptr: unsafe.Pointer(o)}
}

func NewBuiltinModuleFunctionValue(module string, name string, fn NativeFunc, arity int8, variadic bool) Value {
	o := &BuiltinFunction{Func: fn, Module: module, Name: name, Arity: arity, Variadic: variadic}
	return Value{Type: value.BuiltinFunction, Immutable: true, Ptr: unsafe.Pointer(o)}
}

var TypeBuiltinFunction = ValueTypeDescr{
	Name:         builtinFunctionTypeName,
	String:       func(v Value) string { return builtinFunctionTypeName(v) },
	EncodeBinary: builtinFunctionTypeEncodeBinary,
	DecodeBinary: builtinFunctionTypeDecodeBinary,
	IsTrue:       ConstHook(true),
	IsCallable:   ConstHook(true),
	IsVariadic:   builtinFunctionTypeIsVariadic,
	Arity:        builtinFunctionTypeArity,
	Call:         builtinFunctionTypeCall,
	MethodCall:   builtinFunctionTypeMethodCall,
}

func builtinFunctionTypeName(v Value) string {
	o := (*BuiltinFunction)(v.Ptr)
	if o.Variadic {
		if o.Module != "" {
			return fmt.Sprintf("<builtin-function:%s.%s/%d+>", o.Module, o.Name, o.Arity)
		}
		return fmt.Sprintf("<builtin-function:%s/%d+>", o.Name, o.Arity)
	}
	if o.Module != "" {
		return fmt.Sprintf("<builtin-function:%s.%s/%d>", o.Module, o.Name, o.Arity)
	}
	return fmt.Sprintf("<builtin-function:%s/%d>", o.Name, o.Arity)
}

func builtinFunctionTypeEncodeBinary(v Value) ([]byte, error) {
	out := make([]byte, 8)
	binary.BigEndian.PutUint64(out, v.Data)
	return out, nil
}

func builtinFunctionTypeDecodeBinary(v *Value, data []byte) error {
	if len(data) != 8 {
		return fmt.Errorf("builtin function: expected 8 bytes, got %d", len(data))
	}
	v.Data = binary.BigEndian.Uint64(data)
	return nil
}

func builtinFunctionTypeIsVariadic(v Value) bool {
	// no need to check if the index is valid, since it was generated by system
	return (*BuiltinFunction)(v.Ptr).Variadic
}

func builtinFunctionTypeArity(v Value) int8 {
	// no need to check if the index is valid, since it was generated by system
	return (*BuiltinFunction)(v.Ptr).Arity
}

func builtinFunctionTypeCall(vm VM, v Value, args []Value) (Value, error) {
	// no need to check if the index is valid or .Func is not nil, since it was generated by system
	return (*BuiltinFunction)(v.Ptr).Func(vm, args)
}

func builtinFunctionTypeMethodCall(vm VM, v Value, name string, args []Value) (Value, error) {
	switch name {
	case "copy":
		if len(args) != 0 {
			return Undefined, errs.NewWrongNumArgumentsError(name, "0", len(args))
		}
		// it is always immutable, so we can return the same value
		return v, nil

	default:
		return Undefined, errs.NewInvalidMethodError(name, v.TypeName())
	}
}
