package value

const (
	Undefined        = uint8(0) // must be first (zero)
	ValuePtr         = uint8(1)
	BuiltinFunction  = uint8(2)
	BuiltinClosure   = uint8(3)
	CompiledFunction = uint8(4)
	FormatSpec       = uint8(5)
	Error            = uint8(6)
	Bool             = uint8(7)
	Byte             = uint8(8)
	Rune             = uint8(9)
	Int              = uint8(10)
	Float            = uint8(11)
	Decimal          = uint8(12)
	Time             = uint8(13)
	String           = uint8(14)
	Runes            = uint8(15)
	Bytes            = uint8(16)
	Array            = uint8(17)
	Record           = uint8(18)
	Dict             = uint8(19)
	IntRange         = uint8(20)
	RunesIterator    = uint8(21)
	BytesIterator    = uint8(22)
	ArrayIterator    = uint8(23)
	DictIterator     = uint8(24)
	IntRangeIterator = uint8(25)
	UserDefined      = uint8(26) // must be last
)
